[package]
name = "tg-ws-proxy"
version = "1.7.2"
edition = "2024"
resolver = "3"
description = "Telegram Desktop WebSocket Bridge Proxy"
license = "MIT"
authors = ["Flowseal"]

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
native-tls = "0.2"
aes = "0.9"
cipher = "0.5"
ctr = "0.10"
sha2 = "0.11"
hmac = "0.13"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", features = ["json", "native-tls"], default-features = false }
rand = "0.10"
base64 = "0.22"
url = "2"
http = "1"
anyhow = "1"
chrono = "0.4"
toml = "1.1"
parking_lot = "0.12"
dashmap = "6"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tray-icon = "0.24"
crossbeam-channel = "0.5"
image = "0.25"
eframe = { version = "0.34", default-features = false, features = ["glow", "default_fonts"] }
egui = "0.34"
webbrowser = "1"
arboard = "3"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_UI_Shell",
] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
